### ISSUE TITLE
Cropme Ghosting issue

### ISSUE THREAD

**Issue by couldbejake** [shpontex/cropme#12]
While dragging the image in the crop area, there seems to be a trail. This wasn't an issue last week, I'm not sure what's changed. It also applies to the demo.

- Windows 10, Chrome lastest build, JQuery & Bootstrap.

**Comment by couldbejake** [comment]
The image leaves a trail as you drag it in the crop area.

**Comment by pellul** [comment]
Thanks for reporting the bug, it should be ok now.
Please upgrade to 1.3.6 :smiley:
