### ISSUE TITLE
;TypeError: Cannot read property 'mimetype' of undefined' After 'cropMeThis.crop().then(res => {'

### ISSUE THREAD

**Issue by couldbejake** [shpontex/cropme#13]
After attempting to call .crop() on the CropMe instance an error occurs, cropme does not return the res object, I've rolled back the server version to v1.3.4.

**Comment by pellul** [comment]
Oops!
Thanks for reporting, I'm on it.

**Comment by couldbejake** [comment]
Hi will the update for Cropme be available soon, we have a release that's required for tomorrow.

Thanks,
Jake.

**Comment by pellul** [comment]
Sorry for the time it took to fix this, I just had a huge headache.
It should be ok now. :)

**Comment by couldbejake** [comment]
Thank you very much!
++
