### ISSUE TITLE
Image ID delete from DOM after init

### ISSUE THREAD

**Issue by wobility** [shpontex/cropme#15]
Good morning all,

I just found a little bug it seems to me. I'm on the latest version of Google Chrome, but it does the same with Safari. When initializing the cropme the image id is deleted from the DOM. You have to go through another jQuery selector for this to work.

myImage = $ ('. cropme-container> img'). cropme ();

**Comment by shpontex** [comment]
Hi
i fixed the bug and pushed a new 1.4.3 release
(j'essayerai de resoudre le probleme de la rotation des images iphone)
merci pour votre aide :)
