### ISSUE TITLE
How to set position on init ?

### ISSUE THREAD

**Issue by anton-kol** [shpontex/cropme#23]
HTML:
`<img src="/img/photo.jpg" id="avatar" />`

JS:
`var avatar = $('#avatar').cropme();`

How i can to set scale, x, y on page load ?

**Comment by shpontex** [comment]
Hi
you can bind an image and set the scale

var avatar = $('#avatar').cropme();

avatar.cropme('bind', {
  url: 'images/naruto.jpg',
  position: {
    scale: 1.3
  },
});

**Comment by anton-kol** [comment]
it works, thanks!

it would be nice to change position without adding url
