### ISSUE TITLE
Destroy method is not working

### ISSUE THREAD

**Issue by arpitux** [shpontex/cropme#4]
$('#cropme_img').cropme('destroy'); is not working

**Comment by shpontex** [comment]
thank you ill take a look on that

**Comment by shpontex** [comment]
Hi sorry for my late reply
you cannot do $('#cropme_img').cropme('destroy')
you have to do like this :
var myImage = $('#cropme_img').cropme()
then
myImage.cropme('destroy')

sorry the documentation is not clear about that , i will fix it soon
