### ISSUE TITLE
Changing image dpi

### ISSUE THREAD

**Issue by kualee247** [shpontex/cropme#8]
The crop() output seems to default the base64 image to 96dpi. I can't seem to find anything in the js file to adjust the resolution. We need to output image at 300dpi to meet the requirements.
Could you point me in the right direction on how to address this issue?

**Comment by shpontex** [comment]
Hi
the to javascript toDataUrl function output the image to 96 dpi, you cannot change it.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

you can may be use this package to output in 300 dpi
https://www.npmjs.com/package/changedpi
